# Here you can specify default options for TinyMCE across all controllers
#
# theme: advanced
# plugins:
#  - table
#  - fullscreen

theme: advanced
theme_advanced_resizing: true
theme_advanced_resize_horizontal: true
width: 640

plugins:
  - table
  - fullscreen
